### ISSUE TITLE
Ошибка при входе в web-интерфейс

### ISSUE THREAD

**Issue by chsEngineer13** [PilotTeam/pilot-web-client-netcorerelease#25]
Добрый день.
При развертывании docker-контейнеров
docker run --rm -it --name pilot-server -p 5545:5545 -p 80:80 pilotdev/pilot-server:latest

![1](https://user-images.githubusercontent.com/9517310/70978037-19fc5b80-20c0-11ea-9d01-bee551d131fe.png)

Появляется ошибка при входе в web-интерфейс, Pilot-myAdmin и PilotICE-Enterprise работают корректно.

**Comment by InsecureBeast** [comment]
Нужно забрать последний образ (20.0.1) там всё исправлено.
docker run --rm -it --name pilot-server -p 5545:5545 -p 80:80 pilotdev/pilot-server:latest
Предварительно нужно сбросить пароль того пользователя, под которым будет вход в веб-клиент.
