### ISSUE TITLE
Ошибка при аутентификации под доменной учетной записью.

### ISSUE THREAD

**Issue by anasakin** [PilotTeam/pilot-web-client-netcorerelease#26]
Добрый день.
Развернули на IIS.
При входе под локальной учеткой всё ок. При входе под доменной - ошибка на скриншоте.
![image](https://user-images.githubusercontent.com/21291466/72872846-5d6d6980-3cff-11ea-9bdf-fb3e6ca7e231.png)

**Comment by InsecureBeast** [comment]
Добрый день! Посмотрите описание этой ошибки в логе pilot-server.

**Comment by anasakin** [comment]
2020-01-22 10:48:28,555 [194] ERROR [AuthenticationObject] Void Login(System.String, System.String, System.String, Boolean, Int32)
System.DirectoryServices.Protocols.DirectoryOperationException: Сервер не может обработать запросы каталогов.
   в System.DirectoryServices.Protocols.ErrorChecking.CheckAndSetLdapError(Int32 error)
   в System.DirectoryServices.Protocols.LdapSessionOptions.FastConcurrentBind()
   в System.DirectoryServices.AccountManagement.CredentialValidator.BindLdap(NetworkCredential creds, ContextOptions contextOptions)
   в System.DirectoryServices.AccountManagement.CredentialValidator.Validate(String userName, String password)
   в System.DirectoryServices.AccountManagement.PrincipalContext.ValidateCredentials(String userName, String password)
   в Ascon.Pilot.Server.WindowsAuth.Auth(String login, String password)
   в Ascon.Pilot.Server.AuthenticationObject.LoginInternal(String databaseName, String login, String protectedPassword, Boolean useWindowsAuth)
   в Ascon.Pilot.Server.AuthenticationObject.Login(String databaseName, String login, String protectedPassword, Boolean useWindowsAuth, Int32 licenseType)
   в Ascon.Pilot.Server.AuthenticationApiLogger.Login(String databaseName, String login, String protectedPassword, Boolean useWindowsAuth, Int32 licenseType)
2020-01-22 10:48:28,557 [194] INFO  [TransportServer] ProcessRequest error
Ascon.Pilot.Common.PilotServerException: Сервер не может обработать запросы каталогов.
   в Ascon.Pilot.Transport.Unmarshaller.Call(Byte[] data)
   в Ascon.Pilot.Server.Host.HttpServerConnection.Call(Byte[] request)
   в Ascon.Pilot.Transport.Session.ProcessCallRequest(Context context)
   в Ascon.Pilot.Transport.TransportServer.ProcessGetContextAsync(IAsyncResult result)

**Comment by anasakin** [comment]
Еще логи.

2020-01-22 11:14:09,544 [9] ERROR [AccountController] Не удалось подключиться к серверу
System.Exception:     ����          OAscon.Pilot.Common, Version=19.21.0.28918, Culture=neutral, PublicKeyToken=null   'Ascon.Pilot.Common.PilotServerException   	ClassNameMessageDataInnerExceptionHelpURLStackTraceStringRemoteStackTraceStringRemoteStackIndexExceptionMethodHResultSource
WatsonBuckets  System.Collections.IDictionarySystem.Exception      'Ascon.Pilot.Common.PilotServerException   TСервер не может обработать запросы каталогов.


   �   в Ascon.Pilot.Transport.Unmarshaller.Call(Byte[] data)
   в Ascon.Pilot.Server.Host.HttpServerConnection.Call(Byte[] request)
   в Ascon.Pilot.Transport.Session.ProcessCallRequest(Context context)
   в Ascon.Pilot.Transport.TransportServer.ProcessGetContextAsync(IAsyncResult result)
       �8
Call
Ascon.Pilot.Transport, Version=19.21.0.28918, Culture=neutral, PublicKeyToken=null
Ascon.Pilot.Transport.Unmarshaller
Byte[] Call(Byte[]) �   Ascon.Pilot.Transport	      �     C L R 2 0 r 3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 A s c o n . P i l o t . W i n S e r v i c e . e x e                                                                                                                                                                                                                                                                                                                                                                                                                                                                           1 9 . 2 1 . 0 . 2 8 9 1 8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     5 d 2 f 4 e e 8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               A s c o n . P i l o t . S e r v e r                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           1 9 . 2 1 . 0 . 2 8 9 1 8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     e 5 7 9 1 8 7 8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               9 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           8 3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           A s c o n . P i l o t . C o m m o n . P i l o t S e r v e r                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
   at Ascon.Pilot.Transport.MarshallerProxy`1.Invoke(MethodInfo method, Object[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
   at Ascon.Pilot.Web.Models.Context.Connect(Credentials credentials) in D:\Programming\GitHub\pilot-web-client-netcorerelease\Ascon.Pilot.WebClient\src\Ascon.Pilot.Web\Models\Context.cs:line 37
   at Ascon.Pilot.Web.Controllers.AccountController.LogIn(LogInViewModel model) in D:\Programming\GitHub\pilot-web-client-netcorerelease\Ascon.Pilot.WebClient\src\Ascon.Pilot.Web\Controllers\AccountController.cs:line 57

**Comment by InsecureBeast** [comment]
Попробуйте действия описанные в этом вопросе

https://social.msdn.microsoft.com/Forums/azure/en-US/2794fd06-42c7-4b7a-9e44-eafccebbb42b/the-server-cannot-handle-directory-requests-while-using-principalcontextvalidatecrendentials?forum=netfxbcl

**Comment by anasakin** [comment]
Увы, не помогло.

**Comment by InsecureBeast** [comment]
У вас обычный клиент (Pilot-ICE например) может подключиться по доменной учетке?

**Comment by anasakin** [comment]
Да, подключается.
![image](https://user-images.githubusercontent.com/21291466/72889455-c6190e00-3d20-11ea-8a31-80c1d20233af.png)

**Comment by InsecureBeast** [comment]
Это без ввода пароля, я правильно понимаю, а с вводом пароля?

**Comment by anasakin** [comment]
А с вводом проблема повторилась.
![image](https://user-images.githubusercontent.com/21291466/72890084-307e7e00-3d22-11ea-9e21-d4503b8ddf98.png)

**Comment by InsecureBeast** [comment]
Получается у вас не работает NTLM-авторизация. Проверьте настройки сервера Active Directory на работу с NTLM-аутентификацией

**Comment by anasakin** [comment]
Мы используем много систем, где используется NTLM и не сталкивались с подобными трудностями до этого.

**Comment by InsecureBeast** [comment]
Обратитесь с этой ошибкой в службу поддержки Pilot. Т. К. Это не ошибка pilot-web-client, а скорее всего ошибка сервера.

**Comment by anasakin** [comment]
Уже инициировали, спасибо.
